<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" />
    <PackageReference Include="Dapper" />
    <PackageReference Include="Microsoft.Data.SqlClient" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Serilog" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Dapper.ETL.Library\Dapper.ETL.Library.csproj" />
  </ItemGroup>

</Project>
