<Project Sdk="Aspire.AppHost.Sdk/13.1.2">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>3281233e-4963-40c3-a69e-48ac74a7587f</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\bulk-copy-service-aspire-9.0.Server\bulk-copy-service-aspire-9.0.Server.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.JavaScript" Version="13.1.2" />
    <PackageReference Include="Aspire.Hosting.Redis" Version="13.1.2" />
  </ItemGroup>
</Project>
